noun=input("enter noun(place):")
adj1=input("enter adjective (description):")
verb1=input("enter verb (ing):")
adj2=input("enter another adjective:")
verb2=input("enetr another verb:")
print("your short story\n")
print(f"today i went to {noun}")
print(f"there i  saw {adj1} bangles")
print(f"then went to shadab for{verb1}")
print(f"i was {adj2}")
print(f"i also {verb2} some clothes")
